### ISSUE TITLE
Alarm Clock doesn't work properly

### ISSUE THREAD

**Issue by Infinite7Soul** [natsu1211/WeatherAlarm#4]
There is some troubles:
1. Days of repeating are always canceling.
2. Every new alarm clock always switching off after notification
3. After deleting alarm clock I see notification
4. Sometimes after switching off of alarm clock I see notification

**Comment by Infinite7Soul** [comment]
https://drive.google.com/open?id=0B9-ghTf1M_xCQlZqQ08xamt1RGhDQWwyUTZMUlZqOUNyTEZZ

**Comment by natsu1211** [comment]
I found some time to fix this issue.
Please check.

**Comment by Infinite7Soul** [comment]
Hooray! It's working great! Thank you!
