### ISSUE TITLE
Alarm Clock doesn't work after editing

### ISSUE THREAD

**Issue by Infinite7Soul** [natsu1211/WeatherAlarm#5]
If I set Alarm Clock with every day repeating and then I change time I will not receive notification.
https://drive.google.com/open?id=0B9-ghTf1M_xCR0FKRzh1ZWJyR00

**Comment by natsu1211** [comment]
hi,
This is a known issue that i'm not quite sure how to solve :(
I've checked the code and found the `reSchedule()` function is called where it should be. But it is true that notification will not be fired after editing (if you switch off and on the button, it will work properly.)
I am not sure whether i missed something or it's just a bug of APK.
I will rewrite the scheduler using new ios 10 notification, then see whether this issue will be fixed or not.
hope anyone can help.

**Comment by Infinite7Soul** [comment]
Hi!

Thank you so much for reply. I really sorry that I have found so many issues but only you had made alarm clock using swift. There's no any alarm clock templates and I really appreciate your work.

I was testing your app because in my app I need to add scheduled reminders. If you couldn't find a solution I might try to find somebody because my app is almost ready



Отправлено из мобильной Почты Mail.Ru


воскресенье, 26 марта 2017 г., 17:57 +0300 от natsu1211  <notifications@github.com>:

**Comment by natsu1211** [comment]
Glad that this project could help you and thanks so much for the testing.
I really want to solve this long known issue, any help will be appreciated.
